### ISSUE TITLE
Welcome!

### ISSUE THREAD

**Issue by mikeal** [iojs/iojs-ru#1]
Welcome, new localizations team :)

To get this team up and running you have a few initial tasks to accomplish:

- [x] Create a README.md for this repository, it should include:
  - [x] A "call to action" pointing to the Issue tracker for new translators to find tasks.
  - [x] A list of the team members.
  - [x] Instructions on how to log an issue to be added to this team.
- [x] Set the repository description. This should not be in English, it should be in the language for this community :)
- [x] Social Media
 - [x] Create a twitter account for this language. Share the password privately with the team.
 - [x] Create accounts on other social media popular in this language. Share the passwords private with the rest of the team.
 - [ ] Make sure you use these accounts not just to promote newly translated material but also to attract people in your community to help with translation tasks.
- [ ] *Optional:* If you plan to do a Google hangout w/ your localization team have @mikeal add you to the Google+ account so that it can post to the `iojs` YouTube channel. Once you are added there is [documentation on how to setup a hangout-on-air](https://github.com/iojs/io.js/wiki/Meetings:-Creating-a-Hangouts-On-Air-Event).
- [x] Finally, create a new Issue to translate and publish the [latest io.js post](https://medium.com/@iojs). Once translated you should post it wherever you think it will get the most visibility to the community speaking you language, you don't have to post it to Medium unless you think that it is best.

**Comment by YuriSolovyov** [comment]
Not exactly for translation, but Russian node.js/io.js community in vk.com can be found here https://m.vk.com/nodejs_dev_group

**Comment by gorodinskiy** [comment]
all done.
