### ISSUE TITLE
Первый субботник

### ISSUE THREAD

**Issue by gorodinskiy** [iojs/iojs-ru#101]
Итак, давайте на этих выходных займемся чтением одного из разделов документации и его апрувом. Правила простые:
1) все из @iojs/iojs-ru читают в выходные какой-то раздел и делают замечания.
2) после этого если замечаний нет, то раздел принимается в понедельник в репозиторий.

Какой раздел будем читать и обсуждать?

**Comment by YuriSolovyov** [comment]
сегодня глянул кластер и udp, оставил комментарии, в целом вопросов было больше по udp

**Comment by gorodinskiy** [comment]
давайте сегодня завтра читать udp.

**Comment by nrvru** [comment]
Может быть совместно в hangouts будем это делать?

**Comment by gorodinskiy** [comment]
ИМХО, очень сложно это организовать в плане времени

**Comment by YuriSolovyov** [comment]
как-то не вышло( надо конкретнее назначать время. закрываем?

**Comment by Olegas** [comment]
Закрываю. Суббота прошла. И даже следующая )
