### ISSUE TITLE
Еженедельник io.js, 13 марта

### ISSUE THREAD

**Issue by alexpods** [iojs/iojs-ru#102]
Оригинал [тут](https://github.com/iojs/evangelism/blob/b4b80147d86d5d984beb37d7530f79427b5e6f36/weekly-updates/weekly-update.2015-03-13.md) и [тута](https://medium.com/node-js-javascript/io-js-week-of-march-13th-e3024cc66802)

За дело, товарищи @iojs/iojs-ru!

**UPD**:
Аппруверы:
*Cтилистика*: @YuriSolovyov
*Грамматика*: @isRuslan
*Техническая часть*: @gorodinskiy

Менеджер: @Olegas 

Есть вопрос: на собрании обсуждали введение дедлайна для статей?

**Comment by alexpods** [comment]
Перевод в #103

**Comment by gorodinskiy** [comment]
@alexpods поставь кого-нибудь из списка апруверов

**Comment by Olegas** [comment]
http://habrahabr.ru/post/253179/
