### ISSUE TITLE
Начал перевод Stream doc. Требуется уточнение.

### ISSUE THREAD

**Issue by AlexNeodim** [iojs/iojs-ru#104]
Есть несколько вопросов по поводу.
Например, как писать в переводе слово **streams** - во множественном (как есть - **streams** ) 
или в единственном числе (**stream**), для лучшей читаемости**?**

<hr>
Для конкретики, живой пример:
>All **streams** are EventEmitters, but they also..

Здесь **streams** в переводе оставить как есть, или заменить на единственное число**?**
>Все **stream** унаследованы от [EventEmitter][] но они также..

Или все же**?**:
>Все **streams** унаследованы от [EventEmitter][] но они также..

**Comment by Olegas** [comment]
Хм, я бы вообще на русский перевел - Все потоки ...

@iojs/iojs-ru как думаете?

**Comment by YuriSolovyov** [comment]
@AlexNeodim я бы оставлял как в оригинале, если множественное - streams, единственное - stream

**Comment by AlexNeodim** [comment]
@Olegas 
@YuriSolovyov
Тоже склоняюсь к оригиналу, ибо дойдя до конкретных примеров API, может быть не очевидно, что stream - поток. Плюс, люди уже имевшие дело с потоками данных в других языках сами догадаются о чем идёт речь.
Продолжу пока перевод слова как в оригинале.

**Comment by Olegas** [comment]
Ок, ни разу не возражаю
