### ISSUE TITLE
Организационные вопросы

### ISSUE THREAD

**Issue by gorodinskiy** [iojs/iojs-ru#16]
Предлагаю выбрать время и собраться в гиттере или где-нибудь еще, чтобы обсудить следующие вопросы:
1) распределение задач.
2) процесс перевода статей и процесс аппрува этих переводов.
3) аккаунты в соц. сетях. Нужно чтобы и акк на Хабре был не read-only и чтобы твиттер был поактивнее.
4) площадка для временного размещения переводов.(пока что это github pages)
5) отслеживание изменений в оригинале документации.

**Comment by vtambourine** [comment]
Предлагаю в четверг, в 19 по Москве.

**Comment by Olegas** [comment]
Согласен. Можно в чате, можно голосом.

**Comment by gorodinskiy** [comment]
я за четверг, но учтите, что это за день до следующей еженедельной сводки новостей.

**Comment by isRuslan** [comment]
:+1: четверг 19-00 мск

**Comment by Olegas** [comment]
Предлагаю добавить в обсуждение #17

**Comment by YuriSolovyov** [comment]
Уже определились где собирается?
варианты:
- гиттер
- скайп 
- хэнгауты
правда не уверен сколько человек влезет скайп и хэнгауты, если все захотят с голосом

**Comment by gorodinskiy** [comment]
думаю хэнгауты. Там вроде 10 челов влезает.

**Comment by vtambourine** [comment]
Хенгауты проще, не нужно никого добавлять специально в скайп.

**Comment by T0toro** [comment]
Присоеденится можно будет?

**Comment by vtambourine** [comment]
Да, конечно. У вас есть опыт публичных видео-чатов в Хенгауте? 

Я обычно поступаю так — создаю новый видео-чат, копирую публичную ссылку, договариваюсь о том, чтобы в определенное время все желающие перешли по этой ссылке и попали в общий чат. Так же можно поступить и сейчас. Вот ссылка:

https://plus.google.com/hangouts/_/gzxt7csbb5cctrsp6xlzxy44mia

**Comment by YuriSolovyov** [comment]
@vtambourine у меня вот, например, нету опыта

**Comment by vtambourine** [comment]
Но вот я описал рабочий вариант :) В 19 часов по Москве проходите по ссылке. Если будут какие-то проблемы со связью, то их можно решить через Гиттер.

**Comment by Olegas** [comment]
Закрываем?

**Comment by artcygn** [comment]
Я думаю можно закрывать.
