### ISSUE TITLE
Заявка на присоединение к группе переводчиков.

### ISSUE THREAD

**Issue by T0toro** [iojs/iojs-ru#21]
Хочу помочь с переводами статей и документации.

**Comment by isRuslan** [comment]
Привет. Отлично, спасибо :pray:
По поводу процесса, где находятся переводы и как делать информация будет дополняться, пока можно проследить за #16.

На данный момент переводы оформляются пулл реквестами.
Переводы статей из [medium.com/@iojs](https://medium.com/@iojs) располагаются в `medium/`, документация в `public/`.
