### ISSUE TITLE
Статья на Хабр

### ISSUE THREAD

**Issue by gorodinskiy** [iojs/iojs-ru#22]
Нам для инвайта нужна интересная статья. У кого какие идеи?

**Comment by YuriSolovyov** [comment]
можно закрывать https://github.com/iojs/iojs-ru/issues/3#issuecomment-74069041

**Comment by Olegas** [comment]
Считаю что нужно оставить открытой. Несмотря на то, что инвайт получен, ИМХО требуются статьи для Хабра с большим количеством мяса

**Comment by Olegas** [comment]
Кстати, после получения инвайта статья упала в черновики... Наверное надо ее заново опубликовать в нужный хаб?

**Comment by YuriSolovyov** [comment]
Что-нибудь на тему "почему вам стоит использовать/контрибютить в io.js" ? 
Насписать что даже если в какой то момент времени его смерджат обратно в node.js, то всёравно все улучшения попадут туда... ну и стандарную мантру про es6 / новый V8.

Просто можно сразу ванговать комментарии вроде "на node.js можно делать всё то же что и на io.js"  и по большому счёт они будут правы, поэтому кроме es6 отличий пока не так уж и много.

**Comment by T0toro** [comment]
> Кстати, после получения инвайта статья упала в черновики... Наверное надо ее заново опубликовать в нужный хаб?

Да в профильный так как без инвайта постить можно только в песочницу.

**Comment by ReklatsMasters** [comment]
1) Можно сделать статью про отличие от апи nodejs 0.12, что может сломаться при переходе, как дебажить.
2) статью про nan и как правильно перенести нативные расширения, чтоб они собирались на всех версиях.
