### ISSUE TITLE
Перевести assert

### ISSUE THREAD

**Issue by Olegas** [iojs/iojs-ru#26]

**Comment by isRuslan** [comment]
https://crowdin.com/translate/learnyounode-ru/5/en-ru

**Comment by nrvru** [comment]
полный перевод - https://crowdin.com/translate/iojs-ru/4/en-ru

**Comment by Olegas** [comment]
@iojs/iojs-ru давайте смотреть

**Comment by alexpods** [comment]
Несколько правок от меня:

1. Сравнение с приведением типов значений, аналогично сравнению через (==)
=>
Проверка на равенство с приведением типов значений. Аналогично сравнению через (==)
> Tests shallow, coercive equality with the equal comparison operator ( == ).

2. Строгое сравнение на равенство.
=>
Проверка на строгое равенство
> Tests strict equality

3. Глубокое сравнение на неравенство.
=>
Проверка на строгое неравенство
> Tests strict non-equality

4. Глубокое строгое сравнение на равенство.
=>
Проверка на глубокое строгое равенство
> Tests for deep equality

Думаю неплохо все предложения начинающиеся с "Tests for..." в оригинале переводить как "Проверка на..." в переводе.
Если не будет возражений по данным правкам, то позже добавлю в перевод.

**Comment by nrvru** [comment]
Согласен с правками, только еще нужно исправить индекс стабильности на актуальный.

**Comment by Olegas** [comment]
@nrvru может отдельным таском везде поменять разом?

**Comment by nrvru** [comment]
@Olegas Хорошая идея

**Comment by Olegas** [comment]
@nrvru так и я про него (я ж его и сделал ;) )

**Comment by Olegas** [comment]
```
Tests if value is not a false value, throws if it is a true value. Useful when testing the first argument, <0>error</0> in callbacks.
```
Предлагаю
``Выбрасывает исключение, если value эквивалентно true. ...```

**Comment by Olegas** [comment]
А вообще :+1:

**Comment by nrvru** [comment]
@alexpods: Внес все правки. 
@Olegas: Мне кажется, что "бросить исключение" - это жаргонное выражение. В переводах чаще встречал "генерирует исключение", "вызывает исключение" или "создает исключение".

**Comment by Olegas** [comment]
@nrvru ок.

**Comment by Olegas** [comment]
Мержу в #96

**Comment by Olegas** [comment]
Готово
