### ISSUE TITLE
Перевести Cluster

### ISSUE THREAD

**Issue by Olegas** [iojs/iojs-ru#29]
Дополнить:
 - [x] iojs/io.js@87e4bfd582

**Comment by Olegas** [comment]
Начал
https://crowdin.com/translate/iojs-ru/7/en-ru

**Comment by Olegas** [comment]
@iojs/iojs-ru как перевести handle правильно?
Не переводить, оставить хэндл?

**Comment by alexpods** [comment]
@Olegas Как насчет "дескриптор"?

**Comment by Olegas** [comment]
Точно же! Дескриптор! Крутится на языке, никак вспомнить не могу! Спасибо!

**Comment by Olegas** [comment]
Дополнить из апстрима
iojs/io.js@87e4bfd582

**Comment by Olegas** [comment]
@iojs/iojs-ru Можно читать

**Comment by nrvru** [comment]
> To take advantage of multi-core systems the user will sometimes want to launch a cluster of io.js
processes to handle the load.

Чтобы полностью использовать все преимущества многопроцессорной системы и выдерживать большие нагрузки, иногда требуется запустить кластер процессов io.js.
=>
Чтобы  воспользоваться преимуществом многопроцессорных систем пользователю иногда требуется запустить кластер io.js процессов для обработки нагрузки.

**Comment by nrvru** [comment]
> Please try it out and provide feedback.
Пожалуйста попробуйте и дайте обратную связь.
=>
Пожалуйста попробуйте его и оставьте отзыв.

**Comment by T0toro** [comment]
Звучит логически несвязанно:

Данная функциональность представлена недавно и может быть изменена в будущих версиях. Пожалуйста попробуйте и дайте обратную связь.

Думаю лучше так:

Текущие изменения введены недавно и в будущем могут быть изменены. Пожалуйста попробуйте его и оставьте отзыв.

**Comment by nrvru** [comment]
Не переведены коментарии в примерах кода

**Comment by nrvru** [comment]
> Loads have been observed where over 70% of all connections ended up in just two processes,
out of a total of eight.

Наблюдались случаи, когда более 70% всех соединений приходились на только лишь два рабочих процесса из восьми.
=> 
Наблюдались случаи, когда более 70% всех соединений приходились всего лишь на два рабочих процесса из восьми.

**Comment by nrvru** [comment]
>Because workers are all separate processes, they can be killed or
re-spawned depending on your program's needs, without affecting other
workers.

Поскольку рабочие процессы не зависят друг от друга, они могут быть уничтожены или перезапущены в зависимости от потребностей вашей программы, без риска повлиять на других.
=>
Поскольку рабочие процессы не зависят друг от друга, они могут быть остановлены или перезапущены в зависимости от потребностей вашей программы, не затрагивая другие рабочие процессы.

**Comment by nrvru** [comment]
>As long as there are some workers still alive, the server will continue to accept connections.

пока жив => пока существует

**Comment by YuriSolovyov** [comment]
> Рабочий процесс запускается с помощью метода child_process.fork, таким образом они могут общаться с родительским мастер-процессом через IPC и передавать дескрипторы в оба направления.

Рабочие(дочерние? возможно нужно добавить в словарь) процессы запускаются с помощью метода child_process.fork, таким образом они могут общаться с родительским мастер-процессом через IPC и передавать дескрипторы в оба направления.

> Политика распределения нагрузки, cluster.SCHED_RR для карусельного распределения или cluster.SCHED_NONE для распределения силами ОС.

Имхо надо переделать, звучит странно. Возможно что-то типа
Политика распределения может принимать одно из двух значений: (... и далее по тексту)

> значения по умолчанию, указанные выше, применимы только для первого вызова, для последующих вызовов значения по умолчанию будут текущие значения параметров на момент вызова cluster.setupMaster().

значения по умолчанию, указанные выше, применимы только для первого вызова, для последующих вызовов значения**ми** по умолчанию будут текущие значения параметров на момент вызова cluster.setupMaster().

> Когда они будут отключены, все внутренние хэндлы будут закрыты, что позволит мастер-процессу нормально завершиться, если отсутствуют другие ожидающие выполнения события.

хэндлы -> дескрипторы

> Данный метод принимает опциональный колбэк, который будет вызван при завершении.

колбэк -> callback (если я не ошибаюсь на митинге обсудили)

> Хэш, содержащий активные рабочие процессы, с ключом, равным полю id. Позволяет легко перебрать все рабочие процессы. Доступно только в мастер-процессе.

Хэш - новый термин, в оригинале оно тоже как хэш конечно, но имхо тут нужно просто использовать термин объект(в js это и есть хэш).

**Comment by Olegas** [comment]
Все исправил, кроме @T0toro 
```
Текущие изменения введены недавно и в будущем могут быть изменены. Пожалуйста попробуйте и оставьте отзыв.
```

Масло-масляное получается. Оставил первое предложение как было, про отзыв - поправил.

**Comment by Olegas** [comment]
Сделал PR #99 - прогоним через спеллер )

**Comment by Olegas** [comment]
Пардон, каменты я так и не перевел...

**Comment by Olegas** [comment]
Смержено
