### ISSUE TITLE
перевод статьи «io.js Week of February 6th 2015»

### ISSUE THREAD

**Issue by gorodinskiy** [iojs/iojs-ru#3]
Я пока не знаю куда выкатывать статью. Можно завести русскоязычный ресурс.

Перевод можно найти [тут](https://docs.google.com/document/d/1Dfh59I0LnGEpyU0sYYtrTDYIn5aNjwJ48bl3vlJq85c/edit)

**Comment by YuriSolovyov** [comment]
Думаю все переводы должны оформляться в виде пул реквестов

**Comment by vkurchatkin** [comment]
На хабр?

**Comment by YuriSolovyov** [comment]
@vkurchatkin можно

**Comment by gorodinskiy** [comment]
@vkurchatkin отличная идея

**Comment by gorodinskiy** [comment]
Я выложил статью в репозиторий. Там явно много ошибок. Не могли бы вы прочитать?

P.S. @YuriSolovyov прими приглашение в iojs-ru (см. почту)

**Comment by vtambourine** [comment]
Мне кажется, совместные переводы удобнее делать в гуглдоке. Пулреквесты требуют слишком много действий для того, чтобы даже исправить одну маленькую опечатку.

Идеально было бы устроиться на ресурсе, подобном Нотабеноиду.

**Comment by YuriSolovyov** [comment]
@vtambourine имхо для больших кусков перевода лучше делать пул реквесты а для мелкие опечктки можно просто фиксить напрямую

**Comment by gorodinskiy** [comment]
@YuriSolovyov у вас есть право коммитить в репозиторий. Зачем пулл-реквесты?
@vtambourine google docs тоже хороший вариант

**Comment by YuriSolovyov** [comment]
@gorodinskiy для ревью

**Comment by Olegas** [comment]
Всем доброго дня. 

Я бы предложил несколько минорных изменений в перевод, в основном касательно типографики. Пока делаем pull request'ами?

**Comment by gorodinskiy** [comment]
@Olegas давай пока что пулл реквестами.

**Comment by Olegas** [comment]
Ок, сделал #6

**Comment by gorodinskiy** [comment]
@Olegas спасибо, смерджил.

**Comment by gorodinskiy** [comment]
Я создал документ в гугл докс. можно попробовать там его редактировать.
Еще надо подумать о том когда перевод считать готовым.

**Comment by gorodinskiy** [comment]
У нас теперь есть аккаунт на Хабре. Как мы будем определять готовность перевода?

ЗЫ кто-нибудь из вас публиковал что-нибудь на хабре?

**Comment by indutny** [comment]
Я публиковал :) Нужна помощь?

**Comment by Olegas** [comment]
Последний раз я писал на Хабр лет 5 назад ) С тех пор правила там, кажется, сильно поменялись.

**Comment by indutny** [comment]
О, ну тогда и я уже не смогу помочь :)

**Comment by gorodinskiy** [comment]
@indutny просто там вроде много мелочей из-за которых могут сразу «заминусовать». Не хотелось бы первым постом сесть в «минус» =).

Я так понимаю, что habracut нам надо поставить под «Каждую пятницу мы будем публиковать еженедельные новости обо всём, что связано с io.js»

Какие хабы нам надо указать?

Или может у кого есть замечания к переводу?

**Comment by vkurchatkin** [comment]
@gorodinskiy если не обращать внимание на мелочи, то основная ошибка перевода это

> Добавлена поддержка Linux Tracing (LTTNG).

хотя поддержка не добавлена

**Comment by indutny** [comment]
@gorodinskiy думаю, это хорошее место для habracut.

Нужно обязательно публиковать статью как перевод.

А насчет хабов не подскажу. Возможно, нужно будет указать node.js .

**Comment by Olegas** [comment]
По поводу LTTNG исправил (на google docs)

**Comment by Olegas** [comment]
@vkurchatkin давайте и мелочи тоже отполируем чтобы было хорошо.

**Comment by Olegas** [comment]
По поводу Хабра, выдержка из блока о модерации на странице отправки поста:

```
С большой вероятностью не пройдут премодерацию:
— новости и вопросы/просьбы;
```

**Comment by indutny** [comment]
Хм, ну новости про node-webkit я постоянно вижу.

**Comment by gorodinskiy** [comment]
вот [текущая версия](https://docs.google.com/document/d/1Dfh59I0LnGEpyU0sYYtrTDYIn5aNjwJ48bl3vlJq85c/edit)

**Comment by gorodinskiy** [comment]
@indutny а как обозначить что эта статья — перевод? просто указать внизу и дать ссылку?

**Comment by indutny** [comment]
Думаю, нужно ее с самого начала создавать как перевод.

**Comment by gorodinskiy** [comment]
@indutny у нас похоже только «Публикация, претендующая на приглашение» =(

**Comment by indutny** [comment]
Ну тогда нужно дописать, что это перевод :)

**Comment by gorodinskiy** [comment]
Я отправил текущую версию на апрув в Хабре. Теперь надо следить. Если она пройдет надо будет выложить на нее ссылку в твиттере.

**Comment by Olegas** [comment]
Статью разместили в песочнице. http://habrahabr.ru/sandbox/91621/

**Comment by gorodinskiy** [comment]
круто, теперь остается вопрос — что с ней теперь делать. Можем разместить  в твиттере, но новость не актуальна. Надо также просить инвайт на хабр.

**Comment by gorodinskiy** [comment]
пока не решим вопрос с инвайтом, этот баг предлагаю не закрывать

**Comment by Olegas** [comment]
Мне кажется что инвайт за такую статью мы не получим. (

ИМХО надо больше мяса. Например написать как можно с помощью нового LTTNG трейсить процессы. Рисовать потом флеймчарты и чем это отличается от того, что было ранее в Node.

**Comment by gorodinskiy** [comment]
Ну его добавили только вчера. Заведу тогда отдельный тикет на статью. Про эту я так понимаю твитить не будем?

**Comment by T0toro** [comment]
А почему нет?

**Comment by Olegas** [comment]
В общем я затвитил ссылку на перевод на хабре.

**Comment by gorodinskiy** [comment]
хм, мне кажется, что зря

**Comment by Olegas** [comment]
Почему?

**Comment by gorodinskiy** [comment]
имхо, мы больше за нее замечаний получим, а пользы в виде инвайта, нет.

**Comment by gorodinskiy** [comment]
закрываю тикет так как перевод сделали и выложили.

**Comment by Olegas** [comment]
Коллеги, у нас инвайт!

**Comment by gorodinskiy** [comment]
ага, я был не прав. Отличная новость.
