### ISSUE TITLE
аккаунт на habrahabr

### ISSUE THREAD

**Issue by gorodinskiy** [iojs/iojs-ru#4]
Нужно создать отдельный аккаунт на Хабре. Если кто-то может, то создайте и поделитесь паролем со всеми в группе.
[Перевод первой статьи](https://github.com/iojs/iojs-ru/blob/master/medium/io.js%20Week%20of%20February%206th%202015.md) есть, но он еще «сырой».(см. [задачу](https://github.com/iojs/iojs-ru/issues/3))

**Comment by Olegas** [comment]
Займусь.

**Comment by Olegas** [comment]
Аккаунт создан.
Войти можно через твиттер @iojs_ru.
Аккаунт пока на моей почте. Если сделаем отдельную - перекинем. 
Пароль всем вышлю почтой.

**Comment by Olegas** [comment]
iojs_ru

**Comment by Olegas** [comment]
Профиль не заполнен, только аватарку загрузил

**Comment by gorodinskiy** [comment]
супер, спасибо.
