### ISSUE TITLE
Перевести os

### ISSUE THREAD

**Issue by Olegas** [iojs/iojs-ru#44]

**Comment by prog666** [comment]
доделал

**Comment by sidorares** [comment]
> Provides a few basic operating-system related utility functions.
"основных служебныx функций" -> простых функций (или вообще "функций)

остальное :+1:

**Comment by nrvru** [comment]
@prog666:  Returns an array of objects containing information about each CPU/core
installed: model, speed (in MHz), and times (an object containing the number of
milliseconds the CPU/core spent in: user, nice, sys, idle, and irq). -> Возвращает массив объектов, содержащих сведения о каждом установленном процессорe/ядрe: модель, тактовая частота (в МГц) и время (объект, содержащий количество миллисекунд, которое ядро ЦП провело в режиме: user, nice, sys, idle и irq).

**Comment by nrvru** [comment]
Задачу нужно кому-нибудь присвоить, иначе не понятно чей текст основной и кто может редактировать, а кому нужно просто предложения вносить.
Текст довольно сыроват нужно еще раз вычитать.

**Comment by Olegas** [comment]
:+1:

**Comment by Olegas** [comment]
Есть изменения в апстриме 
 io.js/f83d380

**Comment by nrvru** [comment]
Внес все необходимые правки.

**Comment by nrvru** [comment]
Если исправлять в Crowdin слетает форматирование md. Может быть лучше правки вносить через PR?

**Comment by Olegas** [comment]
Точно слетает? Там даже для абзаца xpath выводится! Модет есть какая-то отдельная ссылка для выгрузки?

**Comment by nrvru** [comment]
crowdin оборачивает коды md в <0>,<1> и тд. А вот когда кодов в исходнике нет и оборачивать нечего тогда начинаются проблемы так как текст md в переводе он уже не понимает.

**Comment by Olegas** [comment]
Может быть мы не умеем пользоваться crowdin? Мне кажется в данном случае правильно было бы внести изменения в оригинал и переводить как обычно. Но я не нашел как это можно сделать
/cc @gorodinskiy

**Comment by Olegas** [comment]
@iojs/iojs-ru давайте смотреть

**Comment by alexpods** [comment]
Все ОК :+1:

**Comment by Olegas** [comment]
Смержено
