### ISSUE TITLE
Перевести Path

### ISSUE THREAD

**Issue by Olegas** [iojs/iojs-ru#45]

**Comment by grishaVa** [comment]
Возьму

**Comment by grishaVa** [comment]
Уже готово https://crowdin.com/translate/iojs-ru/24/en-ru

**Comment by Olegas** [comment]
:-1: нужно подробно вычитывать и исправлять.

**Comment by Olegas** [comment]
@iojs/iojs-ru давайте смотреть

**Comment by alexpods** [comment]
Пару правок от меня:

1. Почти все эти методы выполняются только с помощью строковых преобразований.
=> 
Почти все эти методы выполняют только строковые преобразования.
> Almost all these methods perform only string transformations.

2. "normalize" переведено как "упорядочивает". Мне кажется лучше перевести как "нормализует". "Упорядочить" - звучит больше как синоним "отсортировать" (расположить элементы в определенном порядке). "Нормализовать" - привести что-либо в определенное (нормальное) состояние.

3. "absolute path" переведено как "конечный путь". Думаю лучше перевести как "абсолютный путь" или "полный путь". Честно говоря первый раз слышу словосочетание "конечный путь".

4. 
Еще один способ представления cd в качестве команд в оболочке.
=>
Метод может быть представлен как последовательность команд `cd` в командной строке (терминале).
> Another way to think of it is as a sequence of <0>cd</0> commands in a shell.

Если не будет возражений, то позже добавлю в перевод. В остальном вроде все ОК

**Comment by grishaVa** [comment]
Ок, я не против, спасибо за заметки)) 


Вторник, 03 марта 2015, 12:45 -08:00 от Aleksey Podskrebyshev <notifications@github.com>:
>Пару правок от меня:
>* 
>Почти все эти методы выполняются только с помощью строковых преобразований.
>=> 
>Почти все эти методы выполняют только строковые преобразования.
>>Almost all these methods perform only string transformations.
>* 
>"normalize" переведено как "упорядочивает". Мне кажется лучше перевести как "нормализует". "Упорядочить" - звучит больше как синоним "отсортировать" (расположить элементы в определенном порядке). "Нормализовать" - привести что-либо в определенное (нормальное) состояние.
>* 
>"absolute path" переведено как "конечный путь". Думаю лучше перевести как "абсолютный путь" или "полный путь". Честно говоря первый раз слышу словосочетание "конечный путь".
>* 
>Еще один способ представления cd в качестве команд в оболочке.
>=>
>Метод может быть представлен как последовательность команд cd в командной строке (терминале).
>>Another way to think of it is as a sequence of cd0> commands in a shell.
>Если не будет возражений, то позже добавлю в перевод. В остальном вроде все ОК
>—
>Reply to this email directly or  view it on GitHub .


-- 
stranger_V

**Comment by grishaVa** [comment]
Слушай, я переправил, где ты указал, если будут замечания - пиши

**Comment by Olegas** [comment]
Фактическая ошибка:

```
The
resulting path is normalized, and trailing slashes are removed unless the path
gets resolved to the root directory.
```

В результате путь нормализуется и ~~последние косые черты удаляются до тех пор, пока в пути не будет указан корневой каталог.~~

Суть тут была в том, что последняя косая черта удаляется, если только не получился корневой каталог. Тоесть мы не получим никогда тут пустую строку.

```
> require('path').resolve('/a/', '..')
'/'
> require('path').resolve('/a/', 'b/')
'/a/b'
```

**Comment by Olegas** [comment]
```
Если <0>to</0> не полностью абсолютен, аргументы <0>from</0> указывают префикс справа-налево, пока не будет найден абсолютный путь.
```

Реально, смысл тут другой:

```
Если to не является абсолютным, аргументы from перебираются справа на лево до тех пор, пока не будет найден абсолютный путь.
```

**Comment by Olegas** [comment]
:+1: LGTM

**Comment by Olegas** [comment]
Смержил
