### ISSUE TITLE
Вступление в команду переводчиков

### ISSUE THREAD

**Issue by dolphin278** [iojs/iojs-ru#5]
Всем привет, меня зовут Борис Егоров (@dolphin278 здесь и в твиттере).

Хотелось бы поучаствовать в процессе перевода и локализации материалов, связанных с io.js.

Немного о себе:
* Кое-что делал для популяризации node.js в русскоязычном сообществе — участвовал в создании подкаста JSPirates
* сделал довольно популярный в узких кругах модуль `genetic` (генетический алгоритм оптимизации), который используется для решения оптимизационных задач в нескольких компаниях.
* сейчас работаю в компании, которая активно использует node.js в продакшене, и поэтому я  всячески заинтересован способствовать развитию русскоязычного node.js/io.js сообщества.

**Comment by gorodinskiy** [comment]
добавил
