### ISSUE TITLE
Перевести V8

### ISSUE THREAD

**Issue by Olegas** [iojs/iojs-ru#60]

**Comment by T0toro** [comment]
Добавил перевод, также требуется проверка пунктуации.

**Comment by Olegas** [comment]
Нужно вынести перевод в отдельный PR

**Comment by Olegas** [comment]
@iojs/iojs-ru давайте смотреть

**Comment by Olegas** [comment]
Результат в #85

**Comment by Olegas** [comment]
Смержено
