### ISSUE TITLE
Хочу помочь с переводом io.js

### ISSUE THREAD

**Issue by DGizmo** [iojs/iojs-ru#69]

**Comment by isRuslan** [comment]
Привет. Отлично :+1: 

Инструкция по переводу: [вики](https://github.com/iojs/iojs-ru/wiki/Что-делать,-если-вы-хотите-что-то-перевести)

Забираем любую [свободную задачу](https://github.com/iojs/iojs-ru/labels/translation) (@Olegas не считается) с меткой `translation` -> форк -> PR с переводом, частыми коммитами по мере готовности, для того чтобы остальные могли ознакомиться.
