### ISSUE TITLE
Аккаунты в других соцсетях?

### ISSUE THREAD

**Issue by Olegas** [iojs/iojs-ru#7]
Где еще (кроме Хабра #4) можем завести аккаунты?
Группа в FB, VK, G+?

**Comment by gorodinskiy** [comment]
нужно завести акк на Хабре, чтобы было где публиковать.

**Comment by Olegas** [comment]
Имеет смысл делать что-то в соцсетях?

**Comment by gorodinskiy** [comment]
имхо чем больше аккаунтов тем сложнее. Если будем делать встречи, тогда имеет смысл завести группу в ВК.
