### ISSUE TITLE
перевод статьи «io.js Week of February 13th 2015»

### ISSUE THREAD

**Issue by gorodinskiy** [iojs/iojs-ru#71]

**Comment by gorodinskiy** [comment]
я его временно поместил в гуглодоксах. Как только закончу выложу в репу

**Comment by gorodinskiy** [comment]
я добавил перевод в папку medium. Там есть пара спорных моментов:
1) Teams came up with their own ways of working together, and they became more of “community organizers,” as opposed to just “translators” — я убрал вторую часть так как не придумал замены для «организаторов сообщества»
2) We are eager to put this all behind us but we can’t sacrifice the progress we’ve made or the principles and open governance that got us here.
Я бы перевел это как «мы готовы забыть обо всем, но не можем отказаться от того чего добились» или как-то так, но мне кажется, что они имели ввиду что-то другое.

**Comment by Olegas** [comment]
"и это уже не простые переводчики, а организаторы сообщества" ?

**Comment by Olegas** [comment]
Неудобно каментить отдельные комиты (
Еще мне кажется сильно удобнее, когда в PR видно и оригинальный текст

**Comment by gorodinskiy** [comment]
@Olegas  полностью согласен. Я облазил инет в поисках подходящей тулзы, но не нашел. =( Начал переводить в гуглодоке, так там потом конвертировать в html, а тем более в md — полный ад.

Есть пара идей как это всё можно организовать.

**Comment by Olegas** [comment]
Так если все равно переводил один а комментарии в итоге собираем в комитах - есть ли толк в гуглодоксе? 

Может https://github.com/iojs/iojs-ru/wiki/%D0%A7%D1%82%D0%BE-%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C,-%D0%B5%D1%81%D0%BB%D0%B8-%D0%B2%D1%8B-%D1%85%D0%BE%D1%82%D0%B8%D1%82%D0%B5-%D1%87%D1%82%D0%BE-%D1%82%D0%BE-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%B5%D1%81%D1%82%D0%B8 ?

**Comment by gorodinskiy** [comment]
@Olegas я к тому что пробовал разные тулзы. В гуглодоксе переводил, чтобы можно было кинуть всем ссылку и работать с доком вместе еще до того как я его закончу переводить.

**Comment by T0toro** [comment]
> Привлек больше участников чем node.js имел за всю историю и

Привлек больше участников чем node.js за все время его существования

**Comment by T0toro** [comment]
> Как только будет внедрена модель управления вы увидите «тикет» на GitHub о том стоит ли io.js > присоединиться. Обсуждение и голосование по этому вопросу пройдет на публичном заседании > ТК.

Как только будет выбрана оптимальная модель управления, будет проведен опрос на GitHub о том стоит ли io.js присоединиться к node.js. Обсуждение и голосование по этому вопросу пройдет на публичном заседании технического комитета.

**Comment by gorodinskiy** [comment]
я принял ваши изменения, я смогу опубликовать статью только поздно вечером, если кто-то может раньше, то опубликуйте пожалуйста.

**Comment by gorodinskiy** [comment]
опубликовал статью. Попутно узнал о правильном переводе "We are eager to put this all behind us but we can’t sacrifice the progress we’ve made or the principles and open governance that got us here"

Теперь правим на хабре если что.
