### ISSUE TITLE
crowdin.com в качестве инструмента совместной работы?

### ISSUE THREAD

**Issue by sidorares** [iojs/iojs-ru#74]

**Comment by vtambourine** [comment]
Он вроде как стоит денег.

**Comment by sidorares** [comment]
для открытых проектов можно попросить бесплатный план

**Comment by gorodinskiy** [comment]
давайте попросим, и если дадут, то надо всем разослать логин/пароль.

**Comment by sidorares** [comment]
уже - смотрите #25 #32 и обсуждение на гиттер
я, правда, просил в качестве инструмента для learnyounode, так что если есть желание пользоваться предлагаю создать еще проект для iojs ( возможно, один для всех комманд перевода )

**Comment by gorodinskiy** [comment]
https://crowdin.com/project/iojs-ru  заапрувили на opensource лицензию

**Comment by gorodinskiy** [comment]
давайте переносить все туда

**Comment by isRuslan** [comment]
Перенес почти все файлы для документации (все файлы не позволяет текущий план добавить) и последнюю статью из медиума.

https://crowdin.com/project/iojs-ru/ru

То, что уже было сделано для `addons` и `assert` обновил.

**Comment by vtambourine** [comment]
Я не очень понимаю... Я вижу только русский текст, но могу найти оригинала из которого он переведен. Такое ощущение, что все тексты загружены изначально на русском.

**Comment by nrvru** [comment]
В центре в верхнем блоке - "TEXT FOR TRANSLATION"

**Comment by ColCh** [comment]
+1 к crowdin. 

вы ведь ото всех предложения по переводу принимаете?

**Comment by isRuslan** [comment]
@ColCh Конечно.

Ну что, crowdin.com зашел? Можно закрывать?
