### ISSUE TITLE
[ticket] хочу в команду

### ISSUE THREAD

**Issue by ColCh** [iojs/iojs-ru#79]
есть свободное время по воскресениям - готов потратить его во благо переводов

был опыт перевода [кастомной прошивки андроида](https://github.com/ColCh/android_packages_apps_Settings)

**Comment by isRuslan** [comment]
Привет. Супер :pray:

За инструкцией смотрим [вики](https://github.com/iojs/iojs-ru/wiki/Инструкции-для-переводчиков).
