### ISSUE TITLE
поправте описание

### ISSUE THREAD

**Issue by Kvarkas** [iojs/iojs-ru#80]
очепятка: 	Добалвена => 	Добавлена

**Comment by isRuslan** [comment]
Поправьте заголовок.

**Comment by Kvarkas** [comment]
Все еще не исправлено а уже закрыто :) почему?

**Comment by nrvru** [comment]
В тексте коммита?

**Comment by Kvarkas** [comment]
нет, в описании файлов, причем она везде идет автоматом видимо :)

**Comment by nrvru** [comment]
Это не описание файлов, это сообщение коммита с последними изменениями по файлам, у которых это "описание". При следующем коммите с изменениями в этих файлах текст автоматически будет изменен на другое сообщение. Их исправление нетривиальная задача, так как ветка уже ушла далеко вперед.

**Comment by Kvarkas** [comment]
понятно, спасибо за объяснение
