### ISSUE TITLE
перевод io.js Week of February 20th 2015

### ISSUE THREAD

**Issue by gorodinskiy** [iojs/iojs-ru#81]
[https://crowdin.com/translate/iojs-ru/44/en-ru](https://crowdin.com/translate/iojs-ru/44/en-ru)

**Comment by isRuslan** [comment]
Ссылка на статью:
https://medium.com/node-js-javascript/io-js-week-of-february-20th-2015-48486615980

**Comment by Olegas** [comment]
Перевел остатки

**Comment by gorodinskiy** [comment]
супер, я обновил файл в репе. @iojs/iojs-ru Есть у кого-то замечания?

**Comment by nrvru** [comment]
> Набор шифров по-умолчанию, используемый tls и https был изменен и теперь обеспечивает совершенную прямая секретность

Ошибка в слове "прямая". Нужно "прямую" 

Некоторые имена разработчиков на латинице некоторые на кириллице: Amir Saboury, Roman Reiss, William Bert, Скотта Хэммонда, Хиро Асари 

Возможно: LTTing -> LTTng (опечатка в исходнике?)

**Comment by Olegas** [comment]
Исправил все, кроме имен.

Как правильно? Надо ли их переводить или оставлять на английском?

**Comment by nrvru** [comment]
В прошлом выпуске не переводили. Думаю нужно этого и придерживаться

**Comment by gorodinskiy** [comment]
я добавил ссылку на http://roadmap.iojs.org/ в соответствующем пункте.

**Comment by gorodinskiy** [comment]
статья на [хабре](http://habrahabr.ru/post/251197/)

**Comment by gorodinskiy** [comment]
@iojs/iojs-ru у кого есть немного кармы, проголосуйте за пост, чтобы его не слили всякие =)
