### ISSUE TITLE
Требуется перевод дорожной карты развития io.js

### ISSUE THREAD

**Issue by Olegas** [iojs/iojs-ru#84]
См. iojs/roadmap#18

**Comment by gorodinskiy** [comment]
жжешь =)

**Comment by Olegas** [comment]
why ?

**Comment by gorodinskiy** [comment]
«дорожная карта развертывания» смешно звучит)

**Comment by Olegas** [comment]
Э... Я написал развертывания? :)

**Comment by alexpods** [comment]
Перевел и создал пул реквест https://github.com/iojs/roadmap/pull/33. Требуется ревью.

**Comment by alexpods** [comment]
Пулл реквест смержен. Закрываю.
