### ISSUE TITLE
Второе организационное собрание(Вторник 10 марта в 22:00)

### ISSUE THREAD

**Issue by gorodinskiy** [iojs/iojs-ru#87]
Ввиду недавних событий, а именно начала обсуждений о слиянии предлагаю нам устроить хэнгаут митинг и обсудить следующие вопросы:
1. Наше отношение к объединению с node.js и голосование по этому поводу.
2. Процесс аппрува переводов.(мне кажется надо немного изменить этот процесс).
3. Первая сборка сайта с доками на основе уже готовых переводов для русского сообщества.(я постараюсь доделать её до созвона и мы обсудим что есть и как с этим жить)
4. Почта для социальных аккаунтов.
5. Обсуждение правил перевода и составление рекомендации по переводу терминов:
    а) имена людей и их ники
    б) общие термины(форки, пулл-реквесты)
    в) js(типы данных, промисы, область видимости)
    г) общие рекомендации по переводам

**Comment by artcygn** [comment]
На когда планируется?)

**Comment by Olegas** [comment]
:+1:

**Comment by gorodinskiy** [comment]
поставлю @iojs/iojs-ru на всякий пожарный. Если у вас есть еще вопросы для обсуждения пишите.

**Comment by Olegas** [comment]
Нужно установить правила именно перевода.
Например как переводить имена (или не переводить) людей, как переводить названия (или не переводить) типов данных.
Аналогично с "бэджиками" стабильности.
В About this documentation сейчас не так как везде, на сколько я помню

**Comment by Olegas** [comment]
Сюда же видимо про "жаргон". Колбэк или обратный вызов?

**Comment by gorodinskiy** [comment]
@Olegas добавил

**Comment by vtambourine** [comment]
Оргсобрание уже было? Дата еще не известна?

**Comment by gorodinskiy** [comment]
@vtambourine  еще не было, но надо. Предлагаю следующий понедельник 8-го марта в 19 часов.

**Comment by artcygn** [comment]
@gorodinskiy, ты хотел сказать 9-го?

**Comment by vtambourine** [comment]
Как насчет пятницы? Понедельник выходной, кто-то может разъехаться.

**Comment by gorodinskiy** [comment]
давайте тогда во вторник, я до пятницы очень занят по работе

**Comment by Olegas** [comment]
Я готов во вторник.

**Comment by YuriSolovyov** [comment]
а по времени?

**Comment by Olegas** [comment]
Лично я могу в рабочее время (9-18 MSK) или после 22. С 18 до 22 не всегда есть возможность.

**Comment by YuriSolovyov** [comment]
мне удобнее после 22 по мск

**Comment by vtambourine** [comment]
:+1:

**Comment by gorodinskiy** [comment]
давайте во вторник в 22

**Comment by gorodinskiy** [comment]
ссылка для хэнгаутов та же:
https://plus.google.com/hangouts/_/gzxt7csbb5cctrsp6xlzxy44mia

**Comment by alexpods** [comment]
Меня не будет, поэтому вкратце оставлю свое мнение:
1. Скорее отрицательное, чем положительное, но по большей части - всё-равно. В любом случае готов продолжать делать переводы даже. -0 от меня
2. Согласен со схемой предложенной @gorodinskiy в #94 . Можно попробовать, а там видно будет подходит она или нет, и какие есть изъяны.
3. -
4. - 
5. Некоторые мои мысли по поводу правил перевода:

а) имена людей и их ники: 
* если хочешь найти какую-нибудь информацию о человеке, это легче сделать когда знаешь его оригинальное имя.
* в любом случае мы не сможем точно передать произношение имени, оно будет в той или иной степени исковерканным.
* с другой стороны возникают проблемы при склонении имен. Проблему можно обойти добавляя к имени приставку с соответствующим окончанием. (Команда пригласила Rod-а на очередное собрание. О Trevor-е было что-то написано. и тд)
Резюме: думаю переводить не нужно

б) общие термины(форки, пулл-реквесты)
Нужно создать файл vocabulary.md в корне репозитория со списком переводов общих терминов. Вот несколько слов, которые у меня вызывают проблемы с переводом.
* contributors
* natively - в смысле "что-то теперь работает нативно"
* issue
* evangelism - слово "евангелизм" вызвает только религиозные ассоциации
* event loop - можно как "событийный цикл" или "цикл событий". А лучше вообще не переводить.
в) js(типы данных, промисы, область видимости)
* все примитивные типы данных легко переводятся (строки, булевые, числа) за исключением символов (Symbol). Символ - ассоциация со строковым символом, хотя к ним они никакого отношения не имеют
* null, undefined - не переводятся, как и собственно NaN, Infinity, true, false .
* Объекты классов:
    * Array - массив
    * RegExp - регуларное выражение
    * Date - data
    * Function - функция
    * GeneratorFunction - генератор (function*() {})
    * Promise - промисы
    * все остальные называть по названию класса, который не переводится (например "объекты Buffer", "объект WeakMap" и тд).

**Comment by gorodinskiy** [comment]
итоги встречи можно найти [тут](https://github.com/iojs/iojs-ru/wiki/%D0%98%D1%82%D0%BE%D0%B3%D0%B8-%D0%B2%D1%81%D1%82%D1%80%D0%B5%D1%87%D0%B8-10-%D0%BC%D0%B0%D1%80%D1%82%D0%B0-2015)
