### ISSUE TITLE
перевод «io.js Week of February 17th»

### ISSUE THREAD

**Issue by gorodinskiy** [iojs/iojs-ru#88]
оригинал­ — https://medium.com/node-js-javascript/io-js-week-of-february-17th-9422a589302a
перевод — https://crowdin.com/translate/iojs-ru/46/en-ru

**Comment by Olegas** [comment]
Интересно, можно ли для слова "embargoed" применить перевод "огороженный" )

**Comment by gorodinskiy** [comment]
там имеется ввиду, что это некая секьюрная проблема детали, о которой не сообщаются, чтобы нельзя было ее заюзать сейчас.

**Comment by gorodinskiy** [comment]
перевел. Многое пришлось перефразировать(оригинальный текст очень «топорный») Заголовки новостей заменил выделением ключевых слов жирным.

@iojs/iojs-ru читаем и не забываем отписаться в #87, а то до сих пор не обозначили время.

**Comment by alexpods** [comment]
Внес несколько мелких правок. Более крупные хочу обсудить:

1. "Самые главные изменения" => "Основные изменения". Оригинал: "Notable changes"

2. **process** / **promises**: Событие *’unhandledRejection’* происходит на process всякий раз, когда Promise завершается ошибкой,
и соответствующий обработчик не установлен в рамках одного цикла event loop.
=>
**process** / **promises**: Событие *’unhandledRejection’* генерируется объектом process всякий раз, когда Promise завершается ошибкой,
и соответствующий обработчик не установлен в рамках текущей итерации цикла событий.

    *Следующее предложение тоже надо будет поправить, если ввносить данное изменение.**

3. Вообще, как насчет "event loop" переводить как "цикл событий" (так его переводят в [MDN](https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/EventLoop))? Сам сомневаюсь по поводу данного варианта, т.к. "event loop" слышать привычнее. Просто предложение...

4. "Node.js vs io.js: почему вилка?» - Может лучше оставить исходное название "Node.js vs io.js: Why the fork?" ? Или перевести как "Зачем нужен форк"? Прочитал статью, о вилке там речи явно не идет)

**Comment by Olegas** [comment]
3. Мне тоже event loop привычнее (этот абзац как-раз я переводил )). Такие вещи лично мне привычнее видеть в оригинале или в виде как fork -> форк.
4. :+1: за "Зачем нужен форк". Да, в русском языке нет такого слова, но все понимают что это означает.

**Comment by Olegas** [comment]
"ARM связался с Родом Вэггом, ... " - здесь имя переведено, ранее и далее - нет

**Comment by Olegas** [comment]
Исправил несколько мелочей (опечатки).

Немного режет слух "выложил твит"... Может использовать "твитнул"? Или использовать "заявил"? То что это твит - можно понять перейдя по ссылке.

**Comment by gorodinskiy** [comment]
@Olegas я «выложил твит» взял из пердыдущих переводов

**Comment by Olegas** [comment]
Это понятно. Но тем не менее слух режет. Давайте обсудим как это лучше переводить?

**Comment by Ramzec** [comment]
«выложил твит» >> опубликовал в Twitter ??

**Comment by alexpods** [comment]
"опубликовал в твиттере сообщение" звучит вроде неплохо.
Хотя у меня и "выложил твит" не вызывает возражений.

**Comment by Olegas** [comment]
Мне нравится "опубликовал в Twitter".

**Comment by gorodinskiy** [comment]
давай так. Выложите пожалуйста на Хабр. Я не уверен, что у меня будет сегодня-завтра время.

**Comment by alexpods** [comment]
Значит меняем:
Официальный node.js клиент для *Firebase* выложил твит о том, что в версии 2.2.1 добавилась поддержка io.js.
=>
Официальный node.js клиент для *Firebase* опубликовал сообщение в Twitter о том, что в версии 2.2.1 добавилась поддержка io.js.

и выкладываем на Хабр?

Добавил "сообщение" так как "опубликовал в Twitter о том" явно не подходит.

**Comment by Olegas** [comment]
Поменяли? Выкладываем?

**Comment by gorodinskiy** [comment]
мне кажется, что мы уже пропустили момент. Сегодня вечером будет новая подборка.

**Comment by gorodinskiy** [comment]
перевод с правками положил в папку «medium». Тикет закрываю за сроком давности.
