### ISSUE TITLE
перевод «io.js Week of March 6th»

### ISSUE THREAD

**Issue by gorodinskiy** [iojs/iojs-ru#93]
ссылка на оригинал: [io.js Week of March 6th](https://medium.com/node-js-javascript/io-js-week-of-march-6th-2f9344688277)
ссылка на перевод: [https://crowdin.com/translate/iojs-ru/47/en-ru](https://crowdin.com/translate/iojs-ru/47/en-ru)

Есть перевод в пулл реквесте [https://github.com/iojs/iojs-ru/pull/92](https://github.com/iojs/iojs-ru/pull/92)

**Comment by Olegas** [comment]
http://habrahabr.ru/post/252559/
Выложил
